### ISSUE TITLE
Add custom countries and CSS classes?

### ISSUE THREAD

**Issue by sfarfarini** [matteocng/react-flag-icon-css#1]
Hello, I'm migrating an enterprise application UI, that was developed with Angular 1.x, to React.
Since the project was using flag-icon-css I found this nice React component.

The problem is that, for business reasons (the application may manage old patents), the original set of flags was expanded including some meta-countries (like EP for European Patent Office and others) and some former countries that don't exists anymore (like YU for Yugoslavia, SU for Soviet Union or DD for DDR).
I was wondering if there's a way to add to the component my custom countries and flags.

Thanks.

**Comment by matteocng** [comment]
Hi @sfarfarini, thanks for your question. 😄 Custom flags are supported and working, please see the example in the referenced commit. You will have to ignore tcomb's 'Failed prop type' errors (for your custom country codes) in DEV mode for now. I will fix that as soon as I have some time and reference this issue.

**Comment by matteocng** [comment]
Upgrade to version >= 1.0.16 of this module and pass your codes in [customCodes](https://github.com/matteocng/react-flag-icon-css#quick-example); this solves the _prop type_ errors. Feel free to reopen if it doesn't work for you.
