### ISSUE TITLE
Remove Dependancy of prop-types

### ISSUE THREAD

**Issue by atardadi** [matteocng/react-flag-icon-css#110]
### Basic information:

- `react-flag-icon-css` version: 1.0.24
- Module bundler: Webpack version: 4.27.1
- The output of `node -v`: 8.11.3

### Description
Getting the error below when doing `yarn install`
`react-flag-icon-css@1.0.24" has unmet peer dependency "prop-types@^15.6.0"`

I think we can remove this dependancy.

**Comment by matteocng** [comment]
Thanks for reporting @atardadi. Feel free to reopen this issue if the latest release (`1.0.25`) doesn't work for you.
