### ISSUE TITLE
European flag?

### ISSUE THREAD

**Issue by belgac** [matteocng/react-flag-icon-css#2]
Hello i can't seem to find the european flag in the library, there is no code for EU? Am i looking wrong?

**Comment by belgac** [comment]
ok the flag works with eu but isn't referenced in https://github.com/matteocng/react-flag-icon-css/blob/master/static/countries.json

**Comment by matteocng** [comment]
Hello @belgac, thanks for reporting this bug. 😄  The fix is coming later today.

**Comment by matteocng** [comment]
@belgac done, sorry for the delay.
