### ISSUE TITLE
Add TypeScript definition file

### ISSUE THREAD

**Issue by matteocng** [matteocng/react-flag-icon-css#56]
See  [_Including declarations in your npm package_](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

Tests should be added too.

**Comment by jonfreedman** [comment]
Here's a starting point

```typescript
declare module 'react-flag-icon-css' {
    import {PureComponent} from 'react';

    export interface Options {
        useCssModules: boolean;
    }

    export interface FlagIconProps {
        code: string;
        size?: 'lg' | '2x' | '3x' | '4x' | '5x';
        flip?: 'horizontal' | 'vertical';
        rotate?: 30 | 60 | 90 | 180 | 270;
        squared?: boolean;
        className?: string;
        styleName?: string;
    }

    export class FlagIcon extends PureComponent<FlagIconProps> {
    }

    export default function FlagIconFactory(react: any, opts?: Options): () => FlagIcon
}
```

Although as per the various issues around string literal types (e.g. https://github.com/Microsoft/TypeScript/issues/20271) you end up needing to write something like this

```typescript
<FlagIcon code='eu' size={'lg' as 'lg'}/>
```

**Comment by matteocng** [comment]
Hi @jonfreedman thanks for that! It is unfortunate that `TypeScript` has some issues around string literal types (`Flow` too), I don't know if we could make it typecheck computed props too, that would be pretty nice (`size={someSize}`). If you could make a PR please feel free to do so, personally I was looking into [typescript-definition-tester](https://github.com/adamcarr/typescript-definition-tester) to run [a test suite](https://github.com/matteocng/react-flag-icon-css/blob/master/src/__tests__/types/flow.js), but there may be better or more standard ways. Then, after the tests worked (even without custom flags initially), the enum types could be generated like we do with `generate:types` for Flow.

**Comment by jonfreedman** [comment]
Types are now @ https://www.npmjs.com/package/@types/react-flag-icon-css

Please feel free to merge them back into the lib if appropriate

**Comment by matteocng** [comment]
Thanks again @jonfreedman, that is great! 👍
